task:
  name: Hello-World

  env:
    hello_world_env_var: Hello-World
    two_hello: Hello_World${hello_world_env_var}
    hello_world_from_task_name: Hello-${CIRRUS_TASK_NAME#*-}
    hello_world_from_env: Hello-${hello_world_env_var#*-}

  container:
    image: debian:bullseye

  echo_two_hello_script: |
    echo "${two_hello}"

  echo_cirrus_task_name_script: |
    echo "${hello_world_from_task_name}"

  echo_env_script: |
    echo "${hello_world_from_env}"

  echo_default_script: |
    temp_var=Hello-World
    hello_world_from_task=Hello-${temp_var#*-}
    echo "${hello_world_from_task}"
